version: '3.8'
services:
  mysql:
    image: mysql:5.7.31
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/my.cnf:/etc/mysql/my.cnf
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_DATABASE: dockermysql
    networks:
      - symfony
  php-fpm:
    container_name: php-fpm
    privileged: true
    build: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ../:/usr/share/nginx/html
    environment:
      DATABASE_URL: mysql://root:passwd@mysql:3306/dockermysql?serverVersion=5.7
    networks:
      - symfony
    depends_on:
      - mysql
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
    depends_on:
      - php-fpm
networks:
  symfony:
